### ISSUE TITLE
Add baseline support

### ISSUE THREAD

**Issue by artem-zinnatullin** [buildfoundation/bazel_rules_detekt#3]

**Comment by arturdryomov** [comment]
@artem-zinnatullin, what do you mean by the absolute paths issue? From the baseline format it seems like there are no paths, only rules, class and method names.

**Comment by artem-zinnatullin** [comment]
@arturdryomov if I understand correctly, Detekt can use its (Checkstyle-format) XML report it produces as a baseline file. 

Generally, a baseline file allows suppressing certain violations with certain precision like file path, line path, method/class, etc, I'm sure you're well aware of that :)

If you look at the Detekt XML report — it contains absolute paths which are not same across machines and even on one machine between runs due to Bazel sandboxing

There is an upstream issue about that: https://github.com/arturbosch/detekt/issues/853

We can either submit a patch to Detekt to make this configurable or have our wrapper rely on relative paths and convert them to absolute before/after Detekt, I personally prefer patching upstream Detekt so others could benefit from this too

**Comment by arturdryomov** [comment]
Awesome, thanks for the clarification! For some reasons reports I’ve seen on GitHub don’t have paths at all. Will take a closer look and what we can do about it.

**Comment by arturdryomov** [comment]
@artem-zinnatullin, either I’m missing something or your assumption is incorrect. XML reports indeed contain absolute paths but baseline files are different from reports and don’t contain paths. In fact, I haven’t found anything about XML reports being used as baselines.


```console
$ cd tests/integration
$ curl --location https://repo1.maven.org/maven2/io/gitlab/arturbosch/detekt/detekt-cli/1.2.2/detekt-cli-1.2.2-all.jar --output detekt.jar
$ java -jar detekt.jar --baseline detekt-baseline.xml --create-baseline
$ cat detekt-baseline.xml

<?xml version="1.0" ?>
<SmellBaseline>
  <Blacklist></Blacklist>
  <Whitelist>
    <ID>EmptyFunctionBlock:Main.kt${ }</ID>
    <ID>NewLineAtEndOfFile:A.kt$io.buildfoundation.bazelrulesdetekt.integrationtest.A.kt</ID>
  </Whitelist>
</SmellBaseline>
```

So it seems like we can support baselines.

**Comment by artem-zinnatullin** [comment]
`*sprinkles ash on head*`

For some reason I assumed Detekt was a ~good~ static analysis tool that similarly to Android Lint used its own report file as baseline (and I've tried to make it work…)
