### ISSUE TITLE
How to have only one rule for all projects ?

### ISSUE THREAD

**Issue by scorsi** [buildfoundation/bazel_rules_detekt#74]
Hello 👋 

I would like to avoid copying the `detekt` config inside all of my `BUILD` files. Maybe, something like this
#### `/BUILD`
```starlark
load("@rules_detekt//detekt:defs.bzl", "detekt")

detekt(
    name = "detekt",
    srcs = glob(["**/*.kt"]),
    parallel = True,
    disable_default_rulesets = True,
    cfgs = [
        "//:detekt.yml"
    ]
)

exports_files(["detekt.yml", "licence.template"])
```

And when running `bazel build //:detekt` it works for all my sub-projects. Do you have an idea on how I can achieve that ? 

Thanks,

**Comment by Kernald** [comment]
The reason this wouldn't work is that `glob` stops going any deeper as soon as it sees a `BUILD` file in a subfolder.

A solution to doing exactly what you describe would be using [aspects](https://docs.bazel.build/versions/3.3.0/skylark/aspects.html). [This](https://github.com/thundergolfer/bazel-linting-system) repo uses this kind of approach for linters, with a few different examples (nothing Kotlin related, but this should be doable to for Detekt).

But there's another way, which in my opinion is better and matches Bazel's philosophy of having small, highly cacheable targets. You can write a macro for your Kotlin targets, calling both `detekt` and the upstream `kt_jvm_library` or whatever rule you're actually using. You don't have to change or add anything to your library/binary targets (except for the `load` statement), and they all magically get a Detekt target generated for them. You keep small targets (unlike what you would achieve with a top-level `detekt` target, which would have to be ran for every source file as soon as one changes), you can override Detekt's configuration per target if you really need to (and never did but that might happen?), and you can bundle different tools too (e.g. [ktlint](https://ktlint.github.io/)). Such a macro could look like that:

```
def kt_jvm_library(name, srcs, **kwargs):
    upstream_kt_jvm_library(
        name = name,
        srcs = srcs,
        **kwargs
    )

    detekt(
        name = "%s_detekt_report" % name,
        srcs = srcs,
        config = "//java/rules/internal:detekt-config.yml",
    )
```

I wrote an [article](https://enoent.fr/posts/compiling-a-kotlin-application-with-bazel/) covering exactly this, going a little bit more in-depth (also using ktlint, as well as a build test for Detekt targets), which you might find useful.

**Comment by arturdryomov** [comment]
Thanks @Kernald for a response 😉 Generally speaking though — yes, macros are the recommended approach for reusing rules across packages. Bazel tends to be explicit in its declarative behavior to avoid surprises.

**Comment by scorsi** [comment]
@Kernald Why did you use both Ktlint and Detekt ? Does Detekt don't use Ktlint under the hood ? https://detekt.github.io/detekt/formatting.html (I never used Detekt before but it best fit my needs).

I'm a fresh Bazel adopter and so I don't know all the things like macros, thanks for the tips !

I succeed to manage to work with all the stuff you write in your article, but I must admit it missed some part.
 - We need to define a `BUILD` file next to our `defs.bzl` file with `exports_files(["defs.bzl"])` in it to be able to do `load("//path/to/our/defs/folder:defs.bzl", "kt_jvm_library")`.
 - We have to add `bazel_skylib` to the main `WORKSPACE` ([here](https://github.com/bazelbuild/bazel-skylib#workspace-file)).
 - We have to add `load("@bazel_skylib//rules:build_test.bzl", "build_test")` ([here](https://github.com/bazelbuild/bazel-skylib/blob/master/docs/build_test_doc.md)) to the `defs.bzl` file.

**Comment by Kernald** [comment]
Well I started with ktlint and never realised that Detekt was using it! I guess I'll remove it :-)

Thanks for the comments, I'll update the article this weekend! (I really need to work on a minimal example that I could upload somewhere, but 24 hours in a day aren't enough...)

**Comment by scorsi** [comment]
In fact, I'm looking to deal with Detekt options and how I can pass the `io.gitlab.arturbosch.detekt:detekt-formatting` jar into the `detekt` statement.

While looking [here](https://github.com/buildfoundation/bazel_rules_detekt/blob/master/docs/rule.md) it looks like this project doesn't support passing `plugins` options.

I'll keeping investigation and may create a PR with the additional feature and doc to add Ktlint formatting. Since I don't really have the workload actually, you may check this in my place. I'll say when I dive into it.
