### ISSUE TITLE
Unable to fetch transitive closure

### ISSUE THREAD

**Issue by jeffzoch** [buildfoundation/bazel_rules_detekt#91]
When I clone this repo and add it as a local_repository (or a git_repository) via:
```
local_repository(
    name = "rules_detekt",
    path = "../../Tools/bazel_rules_detekt"
)
```

I am unable to build a detekt target after following readme instructions. It just hangs and times out trying to fetch the transitive closure of the 4 dependencies listed and complains its unable to fetch detekt-cli and rxjava. Ive tried adding additional repositories to the maven_install and have verified they exist in each of them - im not sure why it fails.

Is there any chance you plan on doing a release soon? I am on 6232ec84c90a3a737d265128ad35b4b06f32dccb

**Comment by jeffzoch** [comment]
```
/private/var/tmp/_bazel_j.zoch/0b21b737baf5fec332b40ffb25ab9409/execroot/rules_detekt/detekt/wrapper/src/main/kotlin/io/buildfoundation/bazel/detekt/execute/Detekt.kt:3:25: error: unresolved reference: tooling
import io.github.detekt.tooling.api.DetektCli
                        ^
/private/var/tmp/_bazel_j.zoch/0b21b737baf5fec332b40ffb25ab9409/execroot/rules_detekt/detekt/wrapper/src/main/kotlin/io/buildfoundation/bazel/detekt/execute/Detekt.kt:13:13: error: unresolved reference: DetektCli
            DetektCli.load().run(args = args, outputChannel = outputPrinter, errorChannel = errorPrinter)
```
Got the following building all-targets

**Comment by arturdryomov** [comment]
PTAL at the latest version, it might cover your needs.

**Comment by jeffzoch** [comment]
` /private/var/tmp/_bazel_j.zoch/8bdf7aad5539a314ee98a49e42674806/external/rules_detekt/detekt/wrapper/BUILD:15:15: @rules_detekt//detekt/wrapper:lib depends on @rules_detekt_dependencies//:io_gitlab_arturbosch_detekt_detekt_cli in repository @rules_detekt_dependencies which failed to fetch. no such package '@rules_detekt_dependencies//': got 'string' in sequence assignment (want 2-element sequence)`

@arturdryomov im getting the following error. I am following the setup from the readme exactly with no modifications

**Comment by jeffzoch** [comment]
It turns out I had an unrelated change in my workspace's rules_jvm setup that was silly - my  bad
